org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.20.1
forge_version=47.2.0
mod_id=astralium
mod_name=Astralium
mod_version=1.2.3
mod_group_id=com.hirensharma.astralium
mod_authors=Hiren Sharma
mod_description=Discover crystallised starlight in the outer End. Forge Astralium upgrades, master cosmic momentum, and reshape terrain with Shifting Excavation.
