modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="astralium"
version="1.2.5"
displayName="Astralium"
authors="Hiren Sharma"
description='''Discover crystallised starlight in the outer End. NeoForge Astralium upgrades, master cosmic momentum, and reshape terrain with Shifting Excavation.'''

[[dependencies.astralium]]
modId="forge"
mandatory=true
versionRange="[47.1.106,)"
ordering="NONE"
side="BOTH"

[[dependencies.astralium]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"

[[dependencies.astralium]]
modId="curios"
mandatory=true
versionRange="[5.9.1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.astralium]]
modId="jei"
mandatory=false
versionRange="[15.2.0.27,)"
ordering="AFTER"
side="CLIENT"
